version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - app-files:/app_files:z
    command: >
      /bin/sh -c "rm -rf /app_files/* &&
                echo 'Files in /app_files :' &&
                ls -lat /app_files/ &&
                cp -r /app/* /app_files/ &&
                echo 'Files in /app_files :' &&
                ls -lat /app_files/"
  nginx:
    image: nginx:1.19-alpine
    restart: always
    ports:
      - '${NGINX_PORT:-80}:80'
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - app-files:/opt/app:z
    depends_on:
      - app
  puppeteer-renderer:
    image: zenato/puppeteer-renderer
    depends_on:
      - app
volumes:
  app-files:
